export const Status = {
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    DROPPED: "DROPPED",
    DISPUTE: "DISPUTE",
    PENDING: "PENDING",
    IMAGE_PENDING: "IMAGE_PENDING",
    DUPLICATE: "DUPLICATE",
    BANK_MISMATCH: "BANK_MISMATCH",
}