export const languageConfig = {
    en: {
        enterAmountLabel: "Please enter the amount",
        attention: "ATTENTION:",
        attentionEnterAmount: "Enter the amount within the next 10 minutes.",
        enterAmountPlaceholder: "Enter New Amount Here",
        submit: "Submit",
        paymentMethod: "Payment Method",
        attentionSelectMethod: "Select a payment method within the remaining time.",
        upi: "UPI",
        phonePe: "PhonePe",
        gpay: "Google Pay",
        paytm: "Paytm",
        otherUpiApps: "Other UPI Apps",
        bankTransfer: "Bank Transfer",
        invalidAmount: "Error: Amount must be between",
        and: "and",
        accessDeniedTitle: "Access Denied For User!",
        paymentUrlExpiredTitle: "Payment URL Expired!",
        paymentUrlExpiredMessage: "The payment URL you provided has expired. Please generate a new URL and try again.",
        english: "English",
        hindi: "Hindi",
        scanQrCodeToPay: "Scan QR Code to Pay",
        avoidPhonePe: "Avoid depositing through PhonePe for any inconvenience",
        payAmountTo: "Pay",
        to: "to",
        dontHaveApp: "Don’t have the app?",
        copyUpiId: "Copy UPI ID",
        scanQrCode: "Scan the QR code using any UPI app (eg: GPay)",
        verifyAmount: "Verify the payment amount",
        takeScreenshot: "Take a screenshot of your payment and upload or copy 12 digit UTR number and paste in the blank space provided.",
        clickSubmitStart: "Click on",
        clickSubmitEnd: "to complete the process.",
        waitForConfirmation: "Wait for confirmation — your transaction will be verified shortly.",
        stepsForPayment: "Steps for Payment",
        // UtrOrScreenShot keys
        enterUtrNumber: "Enter UTR Number",
        enterUtrOrScreenshot: "Enter UTR or Upload Screenshot",
        fileUploaded: "File uploaded: {fileName}",
        removeFile: "Remove",
        noFileUploaded: "No file uploaded",
        provideUtrOrScreenshot: "Please provide either a UTR number or a screenshot.",
        // BankTransfer keys
        attentionBankDetails: "These details are valid for the next 10 minutes.",
        paymentAfterPeriod: "If payment is made after this period, you will be responsible for any potential losses.",
        paymentUrlExpired: "Payment URL is Expired",
        paymentUrlExpiredTryAgain: "The payment URL has expired. Please try again.",
        paymentSuccess: "Payment has been made successfully",
        pointsCreditedSoon: "Your points will be credited soon in your account",
        transferAmount: "Transfer the displayed Amount using the above details (e.g., IMPS)",
        bankName: "Bank Name",
        accountNumber: "Account Number",
        name: "Name",
        ifscCode: "IFSC Code",
        // NortonAndVideoLink keys
        watchVideoInstructions: "Watch a video for Quick Deposit instructions",
        nortonLogoAlt: "Norton Logo",
        pciLogoAlt: "PCI Logo",
        closeVideo: "Close video",
        quickDepositInstructions: "Quick Deposit Instructions",
        telugu: "Telugu",
        gujarati: "Gujarati",
        bengali: "Bengali",
        hindi: "Hindi",
        tamil: "Tamil",
        english: "English",
        kannada: "Kannada",
        malayalam: "Malayalam",
        amount: "Amount",
        orderId: "Order ID",
        utr: "UTR",
        redirecting: "Redirecting in 5 seconds...",
        enterUtrNumber: "Enter UTR Number",
        SUCCESS_STATUS: "SUCCESS",
        FAILED_STATUS: "FAILED",
        DROPPED_STATUS: "DROPPED",
        DISPUTE_STATUS: "DISPUTE",
        PENDING_STATUS: "PENDING",
        IMAGE_PENDING_STATUS: "IMAGE_PENDING",
        DUPLICATE_STATUS: "DUPLICATE",
        BANK_MISMATCH_STATUS: "BANK_MISMATCH",
        processing: "Your payment is being processed. Please wait until the transaction is confirmed.",
        dispute: "There is a dispute with the payment. Please wait until the transaction is confirmed.",
        duplicate: "Duplicate payment detected. Please wait until the transaction is confirmed.",
        failed: "Payment failed. Please try again with the correct details.",
        expired: "The payment URL has expired. Please try again.",
        success: "Your payment has been successfully processed. Points will be credited soon.",
        paymentUrlExpired: "Payment URL is Expired",
        EXPIRED: "EXPIRED",
        paymentUrlExpiredTryAgain: "The payment URL has expired. Please try again.",
        paymentSuccess: "Payment has been made successfully",
        pointsCreditedSoon: "Your points will be credited soon in your account"
    },
    hi: {
        enterAmountLabel: "कृपया राशि दर्ज करें",
        attention: "ध्यान दें:",
        attentionEnterAmount: "अगले 10 मिनट में राशि दर्ज करें।",
        enterAmountPlaceholder: "यहाँ नई राशि दर्ज करें",
        submit: "जमा करें",
        paymentMethod: "भुगतान विधि",
        attentionSelectMethod: "शेष समय के भीतर भुगतान विधि चुनें।",
        upi: "यूपीआई",
        phonePe: "फोन पे",
        gpay: "जी पे",
        paytm: "पेटीएम",
        otherUpiApps: "अन्य यूपीआई ऐप्स",
        bankTransfer: "बैंक ट्रांसफर",
        invalidAmount: "त्रुटि: राशि इसके बीच होनी चाहिए",
        and: "और",
        accessDeniedTitle: "उपयोगकर्ता के लिए प्रवेश निषिद्ध!",
        paymentUrlExpiredTitle: "भुगतान यूआरएल समाप्त हो गया!",
        paymentUrlExpiredMessage: "आपके द्वारा प्रदान किया गया भुगतान यूआरएल समाप्त हो गया है। कृपया एक नया यूआरएल जनरेट करें और फिर से प्रयास करें।",
        english: "अंग्रेज़ी",
        hindi: "हिंदी",
        scanQrCodeToPay: "क्यूआर कोड स्कैन करें",
        avoidPhonePe: "किसी भी असुविधा के लिए फोनपे के माध्यम से जमा करने से बचें",
        payAmountTo: "भुगतान करें",
        to: "को",
        dontHaveApp: "ऐप नहीं है?",
        copyUpiId: "यूपीआई आईडी कॉपी करें",
        scanQrCode: "किसी भी यूपीआई ऐप का उपयोग करके क्यूआर कोड स्कैन करें (उदाहरण: जी पे)",
        verifyAmount: "भुगतान राशि सत्यापित करें",
        takeScreenshot: "अपने भुगतान का स्क्रीनशॉट लें और अपलोड करें या 12 अंकों का यूटीआर नंबर कॉपी करें और दिए गए स्थान पर पेस्ट करें।",
        clickSubmitStart: "क्लिक करें",
        clickSubmitEnd: "प्रक्रिया पूरी करने के लिए।",
        waitForConfirmation: "पुष्टि की प्रतीक्षा करें — आपका लेनदेन शीघ्र ही सत्यापित हो जाएगा।",
        stepsForPayment: "भुगतान के लिए कदम",
        // UtrOrScreenShot keys
        enterUtrNumber: "UTR नंबर दर्ज करें",
        enterUtrOrScreenshot: "UTR दर्ज करें या स्क्रीनशॉट अपलोड करें",
        fileUploaded: "फ़ाइल अपलोड की गई: {fileName}",
        removeFile: "हटाएँ",
        noFileUploaded: "कोई फ़ाइल अपलोड नहीं की गई",
        provideUtrOrScreenshot: "कृपया UTR नंबर या स्क्रीनशॉट प्रदान करें।",
        // BankTransfer keys
        attentionBankDetails: "ये विवरण अगले 10 मिनट के लिए मान्य हैं।",
        paymentAfterPeriod: "यदि इस अवधि के बाद भुगतान किया जाता है, तो आप किसी भी संभावित नुकसान के लिए जिम्मेदार होंगे।",
        paymentUrlExpired: "भुगतान यूआरएल समाप्त हो गया",
        paymentUrlExpiredTryAgain: "भुगतान यूआरएल समाप्त हो गया है। कृपया फिर से प्रयास करें।",
        paymentSuccess: "भुगतान सफलतापूर्वक हो गया है",
        pointsCreditedSoon: "आपके अंक जल्द ही आपके खाते में जमा हो जाएंगे",
        transferAmount: "ऊपर दिए गए विवरणों का उपयोग करके प्रदर्शित राशि स्थानांतरित करें (उदाहरण: IMPS)",
        bankName: "बैंक का नाम",
        accountNumber: "खाता संख्या",
        name: "नाम",
        ifscCode: "IFSC कोड",
        watchVideoInstructions: "त्वरित जमा निर्देशों के लिए एक वीडियो देखें",
        nortonLogoAlt: "नॉर्टन लोगो",
        pciLogoAlt: "PCI लोगो",
        closeVideo: "वीडियो बंद करें",
        quickDepositInstructions: "त्वरित जमा निर्देश",
        telugu: "तेलुगु",
        gujarati: "गुजराती",
        bengali: "बंगाली",
        hindi: "हिंदी",
        tamil: "तमिल",
        english: "अंग्रेज़ी",
        kannada: "कन्नड़",
        malayalam: "मलयालम",
        processing: "आपका भुगतान संसाधित हो रहा है। कृपया लेनदेन की पुष्टि होने तक प्रतीक्षा करें।",
        dispute: "भुगतान में विवाद है। कृपया लेनदेन की पुष्टि होने तक प्रतीक्षा करें।",
        duplicate: "डुप्लिकेट भुगतान पाया गया है। कृपया लेनदेन की पुष्टि होने तक प्रतीक्षा करें।",
        failed: "भुगतान विफल रहा। कृपया सही विवरण के साथ पुनः प्रयास करें।",
        expired: "भुगतान URL की अवधि समाप्त हो गई है। कृपया पुनः प्रयास करें।",
        success: "आपका भुगतान सफलतापूर्वक संसाधित हो चुका है। अंक शीघ्र ही क्रेडिट किए जाएंगे।",
        amount: "राशि",
        orderId: "आदेश आईडी",
        utr: "यूटीआर",
        redirecting: "5 सेकंड में रीडायरेक्ट हो रहा है...",
        enterUtrNumber: "UTR नंबर दर्ज करें",
        SUCCESS: "सफल",
        FAILED: "विफल",
        DROPPED: "हटाया गया",
        DISPUTE: "विवाद",
        PENDING: "लंबित",
        IMAGE_PENDING: "छवि लंबित",
        DUPLICATE: "डुप्लिकेट",
        BANK_MISMATCH: "बैंक असंगति",
        paymentUrlExpired: "भुगतान यूआरएल समाप्त हो गया",
        EXPIRED: "समाप्त",
        paymentUrlExpiredTryAgain: "भुगतान यूआरएल समाप्त हो गया है। कृपया फिर से प्रयास करें।",
        paymentSuccess: "भुगतान सफलतापूर्वक हो गया है",
        pointsCreditedSoon: "आपके अंक जल्द ही आपके खाते में जमा हो जाएंगे"
    },
    gu: {
        enterAmountLabel: "કૃપા કરીને રકમ દાખલ કરો",
        attention: "ધ્યાન આપો:",
        attentionEnterAmount: "આગામી 10 મિનિટમાં રકમ દાખલ કરો.",
        enterAmountPlaceholder: "અહીં નવી રકમ દાખલ કરો",
        submit: "સબમિટ કરો",
        paymentMethod: "ચુકવણી પદ્ધતિ",
        attentionSelectMethod: "બાકી સમયગાળામાં ચુકવણી પદ્ધતિ પસંદ કરો.",
        upi: "યુપીઆઇ",
        phonePe: "ફોનપે",
        gpay: "જી પે",
        paytm: "પેટીએમ",
        otherUpiApps: "અન્ય યુપીઆઇ એપ્સ",
        bankTransfer: "બેંક ટ્રાન્સફર",
        invalidAmount: "ત્રુટિ: રકમ વચ્ચે હોવી જોઈએ",
        and: "અને",
        accessDeniedTitle: "વપરાશકર્તા માટે પ્રવેશ નકારવામાં આવ્યો!",
        paymentUrlExpiredTitle: "ચુકવણી URL સમાપ્ત થયું!",
        paymentUrlExpiredMessage: "તમે આપેલું ચુકવણી URL સમાપ્ત થઈ ગયું છે. કૃપા કરીને નવું URL જનરેટ કરો અને ફરી પ્રયાસ કરો.",
        english: "અંગ્રેજી",
        hindi: "હિન્દી",
        scanQrCodeToPay: "ક્યૂઆર કોડ સ્કેન કરો",
        avoidPhonePe: "કોઈપણ અસુવિધા માટે ફોનપે દ્વારા જમા કરવાનું ટાળો",
        payAmountTo: "ચૂકવણી કરો",
        to: "ને",
        dontHaveApp: "એપ્લિકેશન નથી?",
        copyUpiId: "યુપીઆઇ આઈડી કૉપિ કરો",
        scanQrCode: "કોઈપણ યુપીઆઇ એપનો ઉપયોગ કરીને ક્યૂઆર કોડ સ્કેન કરો (દા.ત. જી પે)",
        verifyAmount: "ચૂકવણીની રકમ ચકાસો",
        takeScreenshot: "તમારી ચૂકવણીનું સ્ક્રીનશૉટ લો અને અપલોડ કરો અથવા 12 અંકનો યુટીઆર નંબર કૉપિ કરો અને આપેલ જગ્યામાં પેસ્ટ કરો.",
        clickSubmitStart: "ક્લિક કરો",
        clickSubmitEnd: "પ્રક્રિયા પૂર્ણ કરવા માટે।",
        waitForConfirmation: "પુષ્ટિની રાહ જુઓ — તમારું વ્યવહાર ટૂંક સમયમાં ચકાસવામાં આવશે.",
        stepsForPayment: "ચૂકવણી માટેના પગલાં",
        // UtrOrScreenShot keys
        enterUtrNumber: "UTR નંબર દાખલ કરો",
        enterUtrOrScreenshot: "UTR દાખલ કરો અથવા સ્ક્રીનશોટ અપલોડ કરો",
        fileUploaded: "ફાઇલ અપલોડ થઈ: {fileName}",
        removeFile: "દૂર કરો",
        noFileUploaded: "કોઈ ફાઇલ અપલોડ થઈ નથી",
        provideUtrOrScreenshot: "કૃપા કરીને UTR નંબર અથવા સ્ક્રીનશોટ પ્રદાન કરો.",
        // BankTransfer keys
        attentionBankDetails: "આ વિગતો આગામી 10 મિનિટ માટે માન્ય છે.",
        paymentAfterPeriod: "જો આ સમયગાળા પછી ચૂકવણી કરવામાં આવે, તો તમે કોઈપણ સંભવિત નુકસાન માટે જવાબદાર હશો.",
        paymentUrlExpired: "ચુકવણી URL સમાપ્ત થયું",
        paymentUrlExpiredTryAgain: "ચુકવણી URL સમાપ્ત થઈ ગયું છે. કૃપા કરીને ફરી પ્રયાસ કરો.",
        paymentSuccess: "ચૂકવણી સફળતાપૂર્વક થઈ ગઈ છે",
        pointsCreditedSoon: "તમારા પોઈન્ટ્સ ટૂંક સમયમાં તમારા ખાતામાં જમા થશે",
        transferAmount: "ઉપરની વિગતોનો ઉપયોગ કરીને પ્રદર્શિત રકમ ટ્રાન્સફર કરો (દા.ત. IMPS)",
        bankName: "બેંકનું નામ",
        accountNumber: "ખાતા નંબર",
        name: "નામ",
        ifscCode: "IFSC કોડ",
        // NortonAndVideoLink keys
        watchVideoInstructions: "ઝડપી ડિપોઝિટ સૂચનાઓ માટે વિડિઓ જુઓ",
        nortonLogoAlt: "નોર્ટન લોગો",
        pciLogoAlt: "PCI લોગો",
        closeVideo: "વિડિઓ બંધ કરો",
        quickDepositInstructions: "ઝડપી ડિપોઝિટ સૂચનાઓ",
        telugu: "તેલુગુ",
        gujarati: "ગુજરાતી",
        bengali: "બંગાળી",
        hindi: "હિન્દી",
        tamil: "તમિલ",
        english: "ઇંગ્લિશ",
        kannada: "કન્નડા",
        malayalam: "મલયાલમ",
        processing: "તમારું ચુકવણી પ્રોસેસ થઈ રહી છે. કૃપા કરીને ટ્રાન્ઝેક્શનની ચકાસણી થાય ત્યાં સુધી રાહ જુઓ.",
        dispute: "ચુકવણીમાં વિવાદ છે. કૃપા કરીને ટ્રાન્ઝેક્શનની ચકાસણી થાય ત્યાં સુધી રાહ જુઓ.",
        duplicate: "ડુપ્લિકેટ ચુકવણી મળી છે. કૃપા કરીને ટ્રાન્ઝેક્શનની ચકાસણી થાય ત્યાં સુધી રાહ જુઓ.",
        failed: "ચુકવણી નિષ્ફળ ગઈ. કૃપા કરીને સાચા વિગતો સાથે ફરીથી પ્રયાસ કરો.",
        expired: "ચુકવણી URL ની અવધિ સમાપ્ત થઈ ગઈ છે. કૃપા કરીને ફરીથી પ્રયાસ કરો.",
        success: "તમારું ચુકવણી સફળતાપૂર્વક પ્રોસેસ થઈ ગઈ છે. પોઈન્ટ્સ ટૂંક સમયમાં ક્રેડિટ કરવામાં આવશે.",
        amount: "રકમ",
        orderId: "ઓર્ડર આઈડી",
        utr: "યુટીઆર",
        redirecting: "5 સેકન્ડમાં રીડાયરેક્ટ થઈ રહ્યું છે...",
        enterUtrNumber: "UTR નંબર દાખલ કરો",
        SUCCESS: "સફળતા",
        FAILED: "નિષ્ફળ",
        DROPPED: "ડ્રોપ કરેલ",
        DISPUTE: "વિવાદ",
        PENDING: "બાકી",
        IMAGE_PENDING: "ઇમેજ બાકી",
        DUPLICATE: "નકલ",
        BANK_MISMATCH: "બેંક અસંગતતા",
        paymentUrlExpired: "ચુકવણી URL ની મુદત સમાપ્ત થઈ ગઈ છે",
        EXPIRED: "સમાપ્ત",
        paymentUrlExpiredTryAgain: "ચુકવણી URL ની મુદત સમાપ્ત થઈ ગઈ છે. કૃપા કરીને ફરીથી પ્રયાસ કરો.",
        paymentSuccess: "ચુકવણી સફળતાપૂર્વક કરવામાં આવી છે",
        pointsCreditedSoon: "તમારા પોઈન્ટ્સ ટૂંક સમયમાં તમારા ખાતામાં જમા થશે"
    },
    bn: {
        enterAmountLabel: "অনুগ্রহ করে পরিমাণ লিখুন",
        attention: "মনোযোগ দিন:",
        attentionEnterAmount: "পরবর্তী ১০ মিনিটের মধ্যে পরিমাণ লিখুন।",
        enterAmountPlaceholder: "এখানে নতুন পরিমাণ লিখুন",
        submit: "জমা দিন",
        paymentMethod: "পেমেন্ট পদ্ধতি",
        attentionSelectMethod: "বাকি সময়ের মধ্যে একটি পেমেন্ট পদ্ধতি নির্বাচন করুন।",
        upi: "ইউপিআই",
        phonePe: "ফোনপে",
        gpay: "জি পে",
        paytm: "পেটিএম",
        otherUpiApps: "অন্যান্য ইউপিআই অ্যাপ",
        bankTransfer: "ব্যাংক স্থানান্তর",
        invalidAmount: "ত্রুটি: পরিমাণ এর মধ্যে হতে হবে",
        and: "এবং",
        accessDeniedTitle: "ব্যবহারকারীর জন্য প্রবেশ নিষিদ্ধ!",
        paymentUrlExpiredTitle: "পেমেন্ট URL এর মেয়াদ শেষ!",
        paymentUrlExpiredMessage: "আপনার প্রদত্ত পেমেন্ট URL এর মেয়াদ শেষ হয়ে গেছে। একটি নতুন URL তৈরি করুন এবং আবার চেষ্টা করুন।",
        english: "ইংরেজি",
        hindi: "হিন্দি",
        scanQrCodeToPay: "কিউআর কোড স্ক্যান করুন",
        avoidPhonePe: "কোনো অসুবিধার জন্য ফোনপে-র মাধ্যমে জমা দেওয়া এড়িয়ে চলুন",
        payAmountTo: "প্রদান করুন",
        to: "এর কাছে",
        dontHaveApp: "অ্যাপ নেই?",
        copyUpiId: "ইউপিআই আইডি কপি করুন",
        scanQrCode: "যেকোনো ইউপিআই অ্যাপ ব্যবহার করে কিউআর কোড স্ক্যান করুন (যেমন: জি পে)",
        verifyAmount: "পেমেন্টের পরিমাণ যাচাই করুন",
        takeScreenshot: "আপনার পেমেন্টের একটি স্ক্রিনশট নিন এবং আপলোড করুন অথবা ১২ সংখ্যার ইউটিআর নম্বর কপি করে প্রদত্ত স্থানে পেস্ট করুন।",
        clickSubmitStart: "ক্লিক করুন",
        clickSubmitEnd: "প্রক্রিয়াটি সম্পূর্ণ করতে।",
        waitForConfirmation: "নিশ্চিতকরণের জন্য অপেক্ষা করুন — আপনার লেনদেন শীঘ্রই যাচাই করা হবে।",
        stepsForPayment: "পেমেন্টের জন্য ধাপ",
        // UtrOrScreenShot keys
        enterUtrNumber: "ইউটিআর নম্বর লিখুন",
        enterUtrOrScreenshot: "ইউটিআর লিখুন বা স্ক্রিনশট আপলোড করুন",
        fileUploaded: "ফাইল আপলোড হয়েছে: {fileName}",
        removeFile: "মুছে ফেলুন",
        noFileUploaded: "কোনো ফাইল আপলোড হয়নি",
        provideUtrOrScreenshot: "অনুগ্রহ করে ইউটিআর নম্বর বা স্ক্রিনশট প্রদান করুন।",
        // BankTransfer keys
        attentionBankDetails: "এই বিবরণগুলি পরবর্তী ১০ মিনিটের জন্য বৈধ।",
        paymentAfterPeriod: "যদি এই সময়ের পরে পেমেন্ট করা হয়, তবে আপনি যেকোনো সম্ভাব্য ক্ষতির জন্য দায়ী থাকবেন।",
        paymentUrlExpired: "পেমেন্ট URL এর মেয়াদ শেষ",
        paymentUrlExpiredTryAgain: "পেমেন্ট URL এর মেয়াদ শেষ হয়ে গেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        paymentSuccess: "পেমেন্ট সফলভাবে সম্পন্ন হয়েছে",
        pointsCreditedSoon: "আপনার পয়েন্টগুলি শীঘ্রই আপনার অ্যাকাউন্টে জমা হবে",
        transferAmount: "উপরের বিবরণ ব্যবহার করে প্রদর্শিত পরিমাণ স্থানান্তর করুন (যেমন: IMPS)",
        bankName: "ব্যাংকের নাম",
        accountNumber: "অ্যাকাউন্ট নম্বর",
        name: "নাম",
        ifscCode: "IFSC কোড",
        // NortonAndVideoLink keys
        watchVideoInstructions: "দ্রুত জমার নির্দেশাবলীর জন্য একটি ভিডিও দেখুন",
        nortonLogoAlt: "নর্টন লোগো",
        pciLogoAlt: "PCI লোগো",
        closeVideo: "ভিডিও বন্ধ করুন",
        quickDepositInstructions: "দ্রুত জমার নির্দেশাবলী",
        telugu: "তেলুগু",
        gujarati: "গুজরাটি",
        bengali: "বাংলা",
        hindi: "হিন্দি",
        tamil: "তামিল",
        english: "ইংরেজি",
        kannada: "কন্নড়",
        malayalam: "মালায়ালম",
        processing: "আপনার পেমেন্ট প্রক্রিয়াধীন রয়েছে। অনুগ্রহ করে লেনদেন যাচাই করার জন্য অপেক্ষা করুন।",
        dispute: "পেমেন্টে বিরোধ রয়েছে। অনুগ্রহ করে লেনদেন যাচাই করার জন্য অপেক্ষা করুন।",
        duplicate: "ডুপ্লিকেট পেমেন্ট পাওয়া গেছে। অনুগ্রহ করে লেনদেন যাচাই করার জন্য অপেক্ষা করুন।",
        failed: "পেমেন্ট ব্যর্থ হয়েছে। সঠিক বিবরণ দিয়ে আবার চেষ্টা করুন।",
        expired: "পেমেন্ট URL এর মেয়াদ শেষ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        success: "আপনার পেমেন্ট সফলভাবে প্রক্রিয়াজাত হয়েছে। পয়েন্টগুলি শীঘ্রই ক্রেডিট করা হবে।",
        amount: "পরিমাণ",
        orderId: "অর্ডার আইডি",
        utr: "ইউটিআর",
        redirecting: "৫ সেকেন্ডের মধ্যে রিডিরেক্ট হচ্ছে...",
        enterUtrNumber: "ইউটিআর নম্বর লিখুন",
        SUCCESS: "সাফল্য",
        FAILED: "ব্যর্থ",
        DROPPED: "ড্রপ করা হয়েছে",
        DISPUTE: "বিবাদ",
        PENDING: "বিচারাধীন",
        IMAGE_PENDING: "ইমেজ বিচারাধীন",
        DUPLICATE: "নকল",
        BANK_MISMATCH: "ব্যাংক অমিল",
        paymentUrlExpired: "পেমেন্ট URL মেয়াদোত্তীর্ণ হয়েছে",
        EXPIRED: "মেয়াদোত্তীর্ণ",
        paymentUrlExpiredTryAgain: "পেমেন্ট URL মেয়াদোত্তীর্ণ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        paymentSuccess: "পেমেন্ট সফলভাবে সম্পন্ন হয়েছে",
        pointsCreditedSoon: "আপনার পয়েন্টগুলি শীঘ্রই আপনার অ্যাকাউন্টে জমা হবে"
    },
    ta: {
        enterAmountLabel: "தொகையை உள்ளிடவும்",
        attention: "கவனம்:",
        attentionEnterAmount: "அடுத்த 10 நிமிடங்களில் தொகையை உள்ளிடவும்.",
        enterAmountPlaceholder: "புதிய தொகையை இங்கே உள்ளிடவும்",
        submit: "சமர்ப்பிக்கவும்",
        paymentMethod: "கட்டண முறை",
        attentionSelectMethod: "மீதமுள்ள நேரத்தில் கட்டண முறையை தேர்ந்தெடுக்கவும்.",
        upi: "UPI",
        phonePe: "போன்பே",
        gpay: "ஜி பே",
        paytm: "பேடிஎம்",
        otherUpiApps: "மற்ற UPI பயன்பாடுகள்",
        bankTransfer: "வங்கி பரிமாற்றம்",
        invalidAmount: "பிழை: தொகை இதற்கிடையில் இருக்க வேண்டும்",
        and: "மற்றும்",
        accessDeniedTitle: "பயனர் அணுகல் மறுக்கப்பட்டது!",
        paymentUrlExpiredTitle: "கட்டண URL காலாவதி!",
        paymentUrlExpiredMessage: "நீங்கள் வழங்கிய கட்டண URL காலாவதியாகிவிட்டது. புதிய URL ஐ உருவாக்கி மீண்டும் முயற்சிக்கவும்.",
        english: "ஆங்கிலம்",
        hindi: "இந்தி",
        scanQrCodeToPay: "க்யூஆர் குறியீட்டை ஸ்கேன் செய்யவும்",
        avoidPhonePe: "எந்தவொரு சிரமத்திற்கும் PhonePe மூலம் பணம் செலுத்துவதைத் தவிர்க்கவும்",
        payAmountTo: "பணம் செலுத்தவும்",
        to: "க்கு",
        dontHaveApp: "பயன்பாடு இல்லையா?",
        copyUpiId: "UPI ஐடியை நகலெடுக்கவும்",
        scanQrCode: "எந்தவொரு UPI பயன்பாட்டைப் பயன்படுத்தி க்யூஆர் குறியீட்டை ஸ்கேன் செய்யவும் (எ.கா: ஜி பே)",
        verifyAmount: "கட்டணத் தொகையை சரிபார்க்கவும்",
        takeScreenshot: "உங்கள் கட்டணத்தின் ஸ்க்ரீன்ஷாட்டை எடுத்து பதிவேற்றவும் அல்லது 12 இலக்க UTR எண்ணை நகலெடுத்து வழங்கப்பட்ட இடத்தில் ஒட்டவும்.",
        clickSubmitStart: "கிளிக் செய்யவும்",
        clickSubmitEnd: "செயல்முறையை முடிக்க.",
        waitForConfirmation: "உறுதிப்படுத்தலுக்காக காத்திருக்கவும் — உங்கள் பரிவர்த்தனை விரைவில் சரிபார்க்கப்படும்.",
        stepsForPayment: "கட்டணத்திற்கான படிகள்",
        // UtrOrScreenShot keys
        enterUtrNumber: "UTR எண்ணை உள்ளிடவும்",
        enterUtrOrScreenshot: "UTR உள்ளிடவும் அல்லது ஸ்க்ரீன்ஷாட்டை பதிவேற்றவும்",
        fileUploaded: "கோப்பு பதிவேற்றப்பட்டது: {fileName}",
        removeFile: "நீக்கு",
        noFileUploaded: "எந்த கோப்பும் பதிவேற்றப்படவில்லை",
        provideUtrOrScreenshot: "தயவுசெய்து UTR எண்ணை அல்லது ஸ்க்ரீன்ஷாட்டை வழங்கவும்.",
        // BankTransfer keys
        attentionBankDetails: "இந்த விவரங்கள் அடுத்த 10 நிமிடங்களுக்கு செல்லுபடியாகும்.",
        paymentAfterPeriod: "இந்த காலகட்டத்திற்கு பிறகு பணம் செலுத்தப்பட்டால், ஏதேனும் சாத்தியமான இழப்புகளுக்கு நீங்கள் பொறுப்பாவீர்கள்.",
        paymentUrlExpired: "கட்டண URL காலாவதியானது",
        paymentUrlExpiredTryAgain: "கட்டண URL காலாவதியாகிவிட்டது. மீண்டும் முயற்சிக்கவும்.",
        paymentSuccess: "கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது",
        pointsCreditedSoon: "உங்கள் புள்ளிகள் விரைவில் உங்கள் கணக்கில் வரவு வைக்கப்படும்",
        transferAmount: "மேலே உள்ள விவரங்களைப் பயன்படுத்தி காட்டப்பட்ட தொகையை மாற்றவும் (எ.கா: IMPS)",
        bankName: "வங்கியின் பெயர்",
        accountNumber: "கணக்கு எண்",
        name: "பெயர்",
        ifscCode: "IFSC குறியீடு",
        // NortonAndVideoLink keys
        watchVideoInstructions: "விரைவான வைப்பு வழிமுறைகளுக்கு ஒரு வீடியோவைப் பார்க்கவும்",
        nortonLogoAlt: "நார்டன் லோகோ",
        pciLogoAlt: "PCI லோகோ",
        closeVideo: "வீடியோவை மூடு",
        quickDepositInstructions: "விரைவான வைப்பு வழிமுறைகள்",
        telugu: "తెలుగు",
        gujarati: "குஜராத்தி",
        bengali: "பெங்காலி",
        hindi: "ஹிந்தி",
        tamil: "தமிழ்",
        english: "ஆங்கிலம்",
        kannada: "கன்னடம்",
        malayalam: "மலையாளம்",
        processing: "உங்கள் கட்டணம் செயலாக்கப்படுகின்றது. பரிவர்த்தனையை உறுதிப்படுத்தும்போது காத்திருக்கவும்.",
        dispute: "கட்டணத்தில் மோதல் உள்ளது. பரிவர்த்தனையை உறுதிப்படுத்தும்போது காத்திருக்கவும்.",
        duplicate: "பிரதிபலிக்கப்பட்ட கட்டணம் கண்டுபிடிக்கப்பட்டது. பரிவர்த்தனையை உறுதிப்படுத்தும்போது காத்திருக்கவும்.",
        failed: "கட்டணம் தோல்வியடைந்தது. சரியான விவரங்களுடன் மீண்டும் முயற்சிக்கவும்.",
        expired: "கட்டண URL காலாவதியானது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
        success: "உங்கள் கட்டணம் வெற்றிகரமாக செயலாக்கப்பட்டது. புள்ளிகள் விரைவில் வட்டி சேர்க்கப்படும்.",
        amount: "தொகை",
        orderId: "ஆர்டர் ஐடி",
        utr: "யுடிஆர்",
        redirecting: "5 வினாடிகளில் மறுபயனாக்கப்படுகிறது...",
        enterUtrNumber: "UTR எண்ணை உள்ளிடவும்",
        SUCCESS: "வெற்றி",
        FAILED: "தோல்வி",
        DROPPED: "கைவிடப்பட்டது",
        DISPUTE: "விவாதம்",
        PENDING: "நிலுவையில்",
        IMAGE_PENDING: "படம் நிலுவையில்",
        DUPLICATE: "நகல்",
        BANK_MISMATCH: "வங்கி பொருந்தாமை",
        paymentUrlExpired: "கட்டண URL காலாவதியாகிவிட்டது",
        EXPIRED: "காலாவதியானது",
        paymentUrlExpiredTryAgain: "கட்டண URL காலாவதியாகிவிட்டது. மீண்டும் முயற்சிக்கவும்.",
        paymentSuccess: "கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது",
        pointsCreditedSoon: "உங்கள் புள்ளிகள் விரைவில் உங்கள் கணக்கில் வரவு வைக்கப்படும்"

    },
    te: {
        enterAmountLabel: "దయచేసి మొత్తం నమోదు చేయండి",
        attention: "జాగ్రత్త:",
        attentionEnterAmount: "తదుపరి 10 నిమిషాల్లో మొత్తం నమోదు చేయండి.",
        enterAmountPlaceholder: "ఇక్కడ కొత్త మొత్తాన్ని నమోదు చేయండి",
        submit: "సమర్పించండి",
        paymentMethod: "చెల్లింపు విధానం",
        attentionSelectMethod: "మిగిలిన సమయంలో చెల్లింపు విధానాన్ని ఎంచుకోండి.",
        upi: "UPI",
        phonePe: "ఫోన్పే",
        gpay: "జి పే",
        paytm: "పేటీఎం",
        otherUpiApps: "ఇతర UPI యాప్‌లు",
        bankTransfer: "బ్యాంక్ ట్రాన్స్ఫర్",
        invalidAmount: "లోపం: మొత్తం మధ్య ఉండాలి",
        and: "మరియు",
        accessDeniedTitle: "వినియోగదారునికి ప్రవేశం నిరాకరించబడింది!",
        paymentUrlExpiredTitle: "చెల్లింపు URL గడువు ముగిసింది!",
        paymentUrlExpiredMessage: "మీరు అందించిన చెల్లింపు URL గడువు ముగిసింది. దయచేసి కొత్త URL సృష్టించి మళ్లీ ప్రయత్నించండి.",
        english: "ఆంగ్లం",
        hindi: "హిందీ",
        scanQrCodeToPay: "క్యూఆర్ కోడ్‌ను స్కాన్ చేయండి",
        avoidPhonePe: "ఏదైనా అసౌకర్యం కోసం PhonePe ద్వారా డిపాజిట్ చేయడం మానుకోండి",
        payAmountTo: "చెల్లించండి",
        to: "కు",
        dontHaveApp: "యాప్ లేదా?",
        copyUpiId: "UPI ఐడీని కాపీ చేయండి",
        scanQrCode: "ఏదైనా UPI యాప్‌ని ఉపయోగించి క్యూఆర్ కోడ్‌ను స్కాన్ చేయండి (ఉదా: జి పే)",
        verifyAmount: "చెల్లింపు మొత్తాన్ని ధృవీకరించండి",
        takeScreenshot: "మీ చెల్లింపు యొక్క స్క్రీన్‌షాట్ తీసుకొని అప్‌లోడ్ చేయండి లేదా 12 అంకెల UTR నంబర్‌ను కాపీ చేసి అందించిన స్థలంలో అతికించండి.",
        clickSubmitStart: "క్లిక్ చేయండి",
        clickSubmitEnd: "ప్రక్రియను పూర్తి చేయడానికి.",
        waitForConfirmation: "నిర్ధారణ కోసం వేచి ఉండండి — మీ లావాదేవీ త్వరలో ధృవీకరించబడుతుంది.",
        stepsForPayment: "చెల్లింపు కోసం దశలు",
        // UtrOrScreenShot keys
        enterUtrNumber: "UTR నంబర్‌ను నమోదు చేయండి",
        enterUtrOrScreenshot: "UTR నమోదు చేయండి లేదా స్క్రీన్‌షాట్‌ను అప్‌లోడ్ చేయండి",
        fileUploaded: "ఫైల్ అప్‌లోడ్ చేయబడింది: {fileName}",
        removeFile: "తొలగించు",
        noFileUploaded: "ఎటువంటి ఫైల్ అప్‌లోడ్ చేయబడలేదు",
        provideUtrOrScreenshot: "దయచేసి UTR నంబర్ లేదా స్క్రీన్‌షాట్‌ను అందించండి.",
        // BankTransfer keys
        attentionBankDetails: "ఈ వివరాలు తదుపరి 10 నిమిషాల వరకు చెల్లుతాయి.",
        paymentAfterPeriod: "ఈ కాలం తర్వాత చెల్లింపు జరిగితే, ఏవైనా సంభావ్య నష్టాలకు మీరు బాధ్యత వహిస్తారు.",
        paymentUrlExpired: "చెల్లింపు URL గడువు ముగిసింది",
        paymentUrlExpiredTryAgain: "చెల్లింపు URL గడువు ముగిసింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
        paymentSuccess: "చెల్లింపు విజయవంతంగా జరిగింది",
        pointsCreditedSoon: "మీ పాయింట్లు త్వరలో మీ ఖాతాలో జమ అవుతాయి",
        transferAmount: "పైన ఇచ్చిన వివరాలను ఉపయోగించి ప్రదర్శిత మొత్తాన్ని బదిలీ చేయండి (ఉదా: IMPS)",
        bankName: "బ్యాంక్ పేరు",
        accountNumber: "ఖాతా సంఖ్య",
        name: "పేరు",
        ifscCode: "IFSC కోడ్",
        // NortonAndVideoLink keys
        watchVideoInstructions: "త్వరిత డిపాజిట్ సూచనల కోసం వీడియో చూడండి",
        nortonLogoAlt: "నార్టన్ లోగో",
        pciLogoAlt: "PCI లోగో",
        closeVideo: "వీడియో మూసివేయండి",
        quickDepositInstructions: "త్వరిత డిపాజిట్ సూచనలు",
        telugu: "తెలుగు",
        gujarati: "గుజరాతి",
        bengali: "బెంగాలీ",
        hindi: "హిందీ",
        tamil: "తమిళం",
        english: "ఆంగ్లం",
        kannada: "కన్నడ",
        malayalam: "మలయాళం",
        processing: "మీ చెల్లింపు ప్రాసెస్ అవుతోంది. లావాదేవీ నిర్ధారించుకునే వరకు దయచేసి వేచి ఉండండి.",
        dispute: "చెల్లింపులో వివాదం ఉంది. లావాదేవీ నిర్ధారించుకునే వరకు దయచేసి వేచి ఉండండి.",
        duplicate: "డూప్లికేట్ చెల్లింపు కనుగొనబడింది. లావాదేవీ నిర్ధారించుకునే వరకు దయచేసి వేచి ఉండండి.",
        failed: "చెల్లింపు విఫలమైంది. సరైన వివరాలతో మళ్లీ ప్రయత్నించండి.",
        expired: "చెల్లింపు URL గడువు ముగిసింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
        success: "మీ చెల్లింపు విజయవంతంగా ప్రాసెస్ చేయబడింది. పాయింట్లు త్వరలో క్రెడిట్ చేయబడతాయి.",
        amount: "మొత్తం",
        orderId: "ఆర్డర్ ఐడీ",
        utr: "యూటీఆర్",
        redirecting: "5 సెకన్లలో రీడైరెక్ట్ అవుతోంది...",
        enterUtrNumber: "UTR నంబర్‌ను నమోదు చేయండి",
        SUCCESS: "విజయం",
        FAILED: "విఫలం",
        DROPPED: "డ్రాప్ చేయబడింది",
        DISPUTE: "వివాదం",
        PENDING: "పెండింగ్",
        IMAGE_PENDING: "ఇమేజ్ పెండింగ్",
        DUPLICATE: "డూప్లికేట్",
        BANK_MISMATCH: "బ్యాంక్ మిస్మాచ్",
        paymentUrlExpired: "చెల్లింపు URL గడువు ముగిసింది",
        EXPIRED: "గడువు ముగిసింది",
        paymentUrlExpiredTryAgain: "చెల్లింపు URL గడువు ముగిసింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
        paymentSuccess: "చెల్లింపు విజయవంతంగా జరిగింది",
        pointsCreditedSoon: "మీ పాయింట్లు త్వరలో మీ ఖాతాలో జమ అవుతాయి"

    },
    kn: {
        enterAmountLabel: "ದಯವಿಟ್ಟು ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ",
        attention: "ಗಮನಿಸಿ:",
        attentionEnterAmount: "ಮತ್ತಷ್ಟು 10 ನಿಮಿಷಗಳಲ್ಲಿ ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ.",
        enterAmountPlaceholder: "ಇಲ್ಲಿ ಹೊಸ ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ",
        submit: "ಸಲ್ಲಿಸು",
        paymentMethod: "ಪಾವತಿ ವಿಧಾನ",
        attentionSelectMethod: "ಉಳಿದ ಸಮಯದಲ್ಲಿ ಪಾವತಿ ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
        upi: "UPI",
        phonePe: "ಫೋನ್ಪೇ",
        gpay: "ಜಿ ಪೇ",
        paytm: "ಪೇಟಿಎಂ",
        otherUpiApps: "ಇತರ UPI ಆಪ್‌ಗಳು",
        bankTransfer: "ಬ್ಯಾಂಕ್ ಟ್ರಾನ್ಸ್‌ಫರ್",
        invalidAmount: "ದೋಷ: ಮೊತ್ತ ಇವುಗಳ ನಡುವೆ ಇರಬೇಕು",
        and: "ಮತ್ತು",
        accessDeniedTitle: "ಬಳಕೆದಾರರಿಗೆ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ!",
        paymentUrlExpiredTitle: "ಪಾವತಿ URL ಅವಧಿ ಕಳೆದಿದೆ!",
        paymentUrlExpiredMessage: "ನೀವು ನೀಡಿದ ಪಾವತಿ URL ಅವಧಿ ಕಳೆದಿದೆ. ದಯವಿಟ್ಟು ಹೊಸ URL ರಚಿಸಿ ಮತ್ತು ಪುನಃ ಪ್ರಯತ್ನಿಸಿ.",
        english: "ಆಂಗ್ಲ",
        hindi: "ಹಿಂದಿ",
        scanQrCodeToPay: "ಕ್ಯೂಆರ್ ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        avoidPhonePe: "ಯಾವುದೇ ಅನಾನುಕೂಲತೆಗಾಗಿ PhonePe ಮೂಲಕ ಠೇವಣಿ ಮಾಡುವುದನ್ನು ತಪ್ಪಿಸಿ",
        payAmountTo: "ಪಾವತಿಸಿ",
        to: "ಗೆ",
        dontHaveApp: "ಆಪ್ ಇಲ್ಲವೇ?",
        copyUpiId: "UPI ಐಡಿಯನ್ನು ಕಾಪಿ ಮಾಡಿ",
        scanQrCode: "ಯಾವುದೇ UPI ಆಪ್ ಬಳಸಿಕೊಂಡು ಕ್ಯೂಆರ್ ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ (ಉದಾ: ಜಿ ಪೇ)",
        verifyAmount: "ಪಾವತಿ ಮೊತ್ತವನ್ನು ಪರಿಶೀಲಿಸಿ",
        takeScreenshot: "ನಿಮ್ಮ ಪಾವತಿಯ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ತೆಗೆದುಕೊಂಡು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ 12 ಅಂಕಿಗಳ UTR ಸಂಖ್ಯೆಯನ್ನು ಕಾಪಿ ಮಾಡಿ ಮತ್ತು ಒದಗಿಸಲಾದ ಸ್ಥಳದಲ್ಲಿ ಅಂಟಿಸಿ.",
        clickSubmitStart: "ಕ್ಲಿಕ್ ಮಾಡಿ",
        clickSubmitEnd: "ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲು.",
        waitForConfirmation: "ದೃಢೀಕರಣಕ್ಕಾಗಿ ಕಾಯಿರಿ — ನಿಮ್ಮ ವಹಿವಾಟು ಶೀಘ್ರದಲ್ಲೇ ಪರಿಶೀಲಿಸಲ್ಪಡುತ್ತದೆ.",
        stepsForPayment: "ಪಾವತಿಗಾಗಿ ಹಂತಗಳು",
        // UtrOrScreenShot keys
        enterUtrNumber: "UTR ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
        enterUtrOrScreenshot: "UTR ನಮೂದಿಸಿ ಅಥವಾ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        fileUploaded: "ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ: {fileName}",
        removeFile: "ತೆಗೆದುಹಾಕಿ",
        noFileUploaded: "ಯಾವುದೇ ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಆಗಿಲ್ಲ",
        provideUtrOrScreenshot: "ದಯವಿಟ್ಟು UTR ಸಂಖ್ಯೆಯನ್ನು ಅಥವಾ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಒದಗಿಸಿ.",
        // BankTransfer keys
        attentionBankDetails: "ಈ ವಿವರಗಳು ಮುಂದಿನ 10 ನಿಮಿಷಗಳವರೆಗೆ ಮಾನ್ಯವಾಗಿರುತ್ತವೆ.",
        paymentAfterPeriod: "ಈ ಅವಧಿಯ ನಂತರ ಪಾವತಿಯನ್ನು ಮಾಡಿದರೆ, ಯಾವುದೇ ಸಂಭಾವ್ಯ ನಷ್ಟಗಳಿಗೆ ನೀವು ಜವಾಬ್ದಾರರಾಗಿರುತ್ತೀರಿ.",
        paymentUrlExpired: "ಪಾವತಿ URL ಅವಧಿ ಮುಗಿದಿದೆ",
        paymentUrlExpiredTryAgain: "ಪಾವತಿ URL ಅವಧಿ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
        paymentSuccess: "ಪಾವತಿಯು ಯಶಸ್ವಿಯಾಗಿ ಮಾಡಲಾಗಿದೆ",
        pointsCreditedSoon: "ನಿಮ್ಮ ಅಂಕಗಳು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮ ಖಾತೆಗೆ ಜಮಾ ಆಗುತ್ತವೆ",
        transferAmount: "ಮೇಲಿನ ವಿವರಗಳನ್ನು ಬಳಸಿಕೊಂಡು ಪ್ರದರ್ಶಿತ ಮೊತ್ತವನ್ನು ವರ್ಗಾಯಿಸಿ (ಉದಾ: IMPS)",
        bankName: "ಬ್ಯಾಂಕ್‌ನ ಹೆಸರು",
        accountNumber: "ಖಾತೆ ಸಂಖ್ಯೆ",
        name: "ಹೆಸರು",
        ifscCode: "IFSC ಕೋಡ್",
        // NortonAndVideoLink keys
        watchVideoInstructions: "ತ್ವರಿತ ಠೇವಣಿ ಸೂಚನೆಗಳಿಗಾಗಿ ವೀಡಿಯೊ ವೀಕ್ಷಿಸಿ",
        nortonLogoAlt: "ನಾರ್ಟನ್ ಲೋಗೋ",
        pciLogoAlt: "PCI ಲೋಗೋ",
        closeVideo: "ವೀಡಿಯೊ ಮುಚ್ಚಿ",
        quickDepositInstructions: "ತ್ವರಿತ ಠೇವಣಿ ಸೂಚನೆಗಳು",
        telugu: "ತೆಲುಗು",
        gujarati: "ಗುಜರಾತಿ",
        bengali: "ಬಂಗಾಳಿ",
        hindi: "ಹಿಂದಿ",
        tamil: "ತಮಿಳು",
        english: "ಇಂಗ್ಲಿಷ್",
        kannada: "ಕನ್ನಡ",
        malayalam: "ಮಲಯಾಳಂ",
        processing: "ನಿಮ್ಮ ಪಾವತಿ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ ಇದೆ. ದಯವಿಟ್ಟು ವ್ಯವಹಾರ ಪರಿಶೀಲನೆಗಾಗಿಯೇ ಕಾಯಿರಿ.",
        dispute: "ಪಾವತಿಯಲ್ಲಿ ವಿವಾದವಿದೆ. ದಯವಿಟ್ಟು ವ್ಯವಹಾರ ಪರಿಶೀಲನೆಗಾಗಿಯೇ ಕಾಯಿರಿ.",
        duplicate: "ನಕಲಿ ಪಾವತಿ ಕಂಡುಬಂದಿದೆ. ದಯವಿಟ್ಟು ವ್ಯವಹಾರ ಪರಿಶೀಲನೆಗಾಗಿಯೇ ಕಾಯಿರಿ.",
        failed: "ಪಾವತಿ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಸರಿಯಾದ ವಿವರಗಳೊಂದಿಗೆ ಪುನಃ ಪ್ರಯತ್ನಿಸಿ.",
        expired: "ಪಾವತಿ URL ಅವಧಿ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
        success: "ನಿಮ್ಮ ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿ ಪ್ರಕ್ರಿಯೆಯಾಗಿದೆ. ಅಂಕಗಳನ್ನು ಶೀಘ್ರದಲ್ಲೇ ಕ್ರೆಡಿಟ್ ಮಾಡಲಾಗುವುದು.",
        amount: "ಮೊತ್ತ",
        orderId: "ಆರ್ಡರ್ ಐಡಿ",
        utr: "ಯುಟಿಆರ್",
        redirecting: "5 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಮರುನಿರ್ದೇಶನಗೊಳ್ಳುತ್ತಿದೆ...",
        enterUtrNumber: "UTR ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
        SUCCESS: "ಯಶಸ್ಸು",
        FAILED: "ವಿಫಲವಾಗಿದೆ",
        DROPPED: "ಬಿಡಲಾಗಿದೆ",
        DISPUTE: "ವಿವಾದ",
        PENDING: "ಬಾಕಿ",
        IMAGE_PENDING: "ಚಿತ್ರ ಬಾಕಿ",
        DUPLICATE: "ನಕಲು",
        BANK_MISMATCH: "ಬ್ಯಾಂಕ್ ಹೊಂದಾಣಿಕೆಯಾಗುವುದಿಲ್ಲ",
        paymentUrlExpired: "ಪಾವತಿ URL ಅವಧಿ ಮುಗಿದಿದೆ",
        EXPIRED: "ಅವಧಿ ಮುಗಿದಿದೆ",
        paymentUrlExpiredTryAgain: "ಪಾವತಿ URL ಅವಧಿ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
        paymentSuccess: "ಪಾವತಿಯು ಯಶಸ್ವಿಯಾಗಿ ಮಾಡಲಾಗಿದೆ",
        pointsCreditedSoon: "ನಿಮ್ಮ ಪಾಯಿಂಟ್‌ಗಳು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮ ಖಾತೆಗೆ ಜಮೆಯಾಗುತ್ತವೆ"

    },
    ml: {
        enterAmountLabel: "ദയവായി തുക നൽകുക",
        attention: "ശ്രദ്ധിക്കുക:",
        attentionEnterAmount: "അടുത്ത 10 മിനിറ്റിനുള്ളിൽ തുക നൽകുക.",
        enterAmountPlaceholder: "ഇവിടെ പുതിയ തുക നൽകുക",
        submit: "സമർപ്പിക്കുക",
        paymentMethod: "പേയ്മെന്റ് വിധി",
        attentionSelectMethod: "ബാക്കിയായ സമയത്തിനുള്ളിൽ പേയ്മെന്റ് വിധി തിരഞ്ഞെടുക്കുക.",
        upi: "UPI",
        phonePe: "ഫോൺപേ",
        gpay: "ജി പേ",
        paytm: "പേടിഎം",
        otherUpiApps: "മറ്റ് UPI ആപ്പുകൾ",
        bankTransfer: "ബാങ്ക് ട്രാൻസ്ഫർ",
        invalidAmount: "പിശക്: തുക ഇതിന് ഇടയിൽ ആയിരിക്കണം",
        and: "ഉം",
        accessDeniedTitle: "ഉപയോക്താവിന് പ്രവേശനം നിരസിച്ചു!",
        paymentUrlExpiredTitle: "പേയ്‌മെന്റ് URL കാലഹരണപ്പെട്ടു!",
        paymentUrlExpiredMessage: "നിങ്ങൾ നൽകിയ പേയ്‌മെന്റ് URL കാലഹരണപ്പെട്ടിട്ടുണ്ട്. പുതിയതൊന്ന് സൃഷ്ടിച്ച് വീണ്ടും ശ്രമിക്കുക.",
        english: "ഇംഗ്ലീഷ്",
        hindi: "ഹിന്ദി",
        scanQrCodeToPay: "ക്യൂആർ കോഡ് സ്കാൻ ചെയ്യുക",
        avoidPhonePe: "ഏതെങ്കിലും അസൗകര്യത്തിന് ഫോൺപേ വഴി നിക്ഷേപിക്കുന്നത് ഒഴിവാക്കുക",
        payAmountTo: "പണം നൽകുക",
        to: "ന്",
        dontHaveApp: "ആപ്പ് ഇല്ലേ?",
        copyUpiId: "UPI ഐഡി പകർത്തുക",
        scanQrCode: "ഏതെങ്കിലും UPI ആപ്പ് ഉപയോഗിച്ച് ക്യൂആർ കോഡ് സ്കാൻ ചെയ്യുക (ഉദാ: ജി പേ)",
        verifyAmount: "പേയ്‌മെന്റ് തുക പരിശോധിക്കുക",
        takeScreenshot: "നിന്റെ പേയ്‌മെന്റിന്റെ സ്ക്രീൻഷോട്ട് എടുത്ത് അപ്‌ലോഡ് ചെയ്യുക അല്ലെങ്കിൽ 12 അക്ക UTR നമ്പർ പകർത്തി നൽകിയിടത്ത് ഒട്ടിക്കുക.",
        clickSubmitStart: "ക്ലിക്ക് ചെയ്യുക",
        clickSubmitEnd: "പ്രക്രിയ പൂർത്തിയാക്കാൻ.",
        waitForConfirmation: "സ്ഥിരീകരണത്തിനായി കാത്തിരിക്കുക — നിന്റെ ഇടപാട് ഉടൻ പരിശോധിക്കപ്പെടും.",
        stepsForPayment: "പേയ്‌മെന്റിനുള്ള ഘട്ടങ്ങൾ",
        // UtrOrScreenShot keys
        enterUtrNumber: "UTR നമ്പർ നൽകുക",
        enterUtrOrScreenshot: "UTR നൽകുക അല്ലെങ്കിൽ സ്ക്രീൻഷോട്ട് അപ്‌ലോഡ് ചെയ്യുക",
        fileUploaded: "ഫയൽ അപ്‌ലോഡ് ചെയ്തു: {fileName}",
        removeFile: "നീക്കം ചെയ്യുക",
        noFileUploaded: "ഒരു ഫയലും അപ്‌ലോഡ് ചെയ്തിട്ടില്ല",
        provideUtrOrScreenshot: "ദയവായി UTR നമ്പർ അല്ലെങ്കിൽ സ്ക്രീൻഷോട്ട് നൽകുക.",
        // BankTransfer keys
        attentionBankDetails: "ഈ വിശദാംശങ്ങൾ അടുത്ത 10 മിനിറ്റിനുള്ളിൽ സാധുവാണ്.",
        paymentAfterPeriod: "ഈ കാലയളവിന് ശേഷം പണമടച്ചാൽ, ഏതെങ്കിലും സാധ്യമായ നഷ്ടങ്ങൾക്ക് നിന്നെ ഉത്തരവാദിയാകും.",
        paymentUrlExpired: "പേയ്‌മെന്റ് URL കാലഹരണപ്പെട്ടു",
        paymentUrlExpiredTryAgain: "പേയ്‌മെന്റ് URL കാലഹരണപ്പെട്ടു. വീണ്ടും ശ്രമിക്കുക.",
        paymentSuccess: "പേയ്‌മെന്റ് വിജയകരമായി നടന്നു",
        pointsCreditedSoon: "നിന്റെ പോയിന്റുകൾ ഉടൻ നിന്റെ അക്കൗണ്ടിൽ ക്രെഡിറ്റ് ചെയ്യപ്പെടും",
        transferAmount: "മുകളിൽ നൽകിയ വിശദാംശങ്ങൾ ഉപയോഗിച്ച് പ്രദർശിപ്പിച്ച തുക കൈമാറുക (ഉദാ: IMPS)",
        bankName: "ബാങ്കിന്റെ പേര്",
        accountNumber: "അക്കൗണ്ട് നമ്പർ",
        name: "പേര്",
        ifscCode: "IFSC കോഡ്",
        // NortonAndVideoLink keys
        watchVideoInstructions: "വേഗത്തിലുള്ള നിക്ഷേപ നിർദ്ദേശങ്ങൾക്കായി ഒരു വീഡിയോ കാണുക",
        nortonLogoAlt: "നോർട്ടൻ ലോഗോ",
        pciLogoAlt: "PCI ലോഗോ",
        closeVideo: "വീഡിയോ അടയ്ക്കുക",
        quickDepositInstructions: "വേഗത്തിലുള്ള നിക്ഷേപ നിർദ്ദേശങ്ങൾ",
        telugu: "തെലുങ്ക്",
        gujarati: "ഗുജറാത്തി",
        bengali: "ബംഗാളി",
        hindi: "ഹിന്ദി",
        tamil: "തമിഴ്",
        english: "ഇംഗ്ലീഷ്",
        kannada: "കന്നഡ",
        malayalam: "മലയാളം",
        processing: "നിങ്ങളുടെ പെയ്മെന്റ് പ്രോസസ്സിൽ ആണ്. ഇടപാട് സ്ഥിരീകരിക്കുന്നതുവരെ കാത്തിരിക്കുക.",
        dispute: "പെയ്മെന്റിൽ തർക്കം ഉണ്ട്. ഇടപാട് സ്ഥിരീകരിക്കുന്നതുവരെ കാത്തിരിക്കുക.",
        duplicate: "പുനരാവൃത പെയ്മെന്റ് കണ്ടെത്തിയിരിക്കുന്നു. ഇടപാട് സ്ഥിരീകരിക്കുന്നതുവരെ കാത്തിരിക്കുക.",
        failed: "പെയ്മെന്റ് പരാജയപ്പെട്ടു. ശരിയായ വിവരങ്ങളോടെ വീണ്ടും ശ്രമിക്കുക.",
        expired: "പെയ്മെന്റ് URL കാലാവധി കഴിഞ്ഞിരിക്കുന്നു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
        success: "നിങ്ങളുടെ പെയ്മെന്റ് വിജയകരമായി പ്രോസസ് ചെയ്തു. പോയിന്റുകൾ ഉടൻ ക്രെഡിറ്റ് ചെയ്യപ്പെടും.",
        amount: "തുക",
        orderId: "ഓർഡർ ഐഡി",
        utr: "യുടിആർ",
        redirecting: "5 സെക്കൻഡിനുള്ളിൽ റീഡയറക്ട് ചെയ്യുന്നു...",
        enterUtrNumber: "UTR നമ്പർ നൽകുക",
        SUCCESS: "വിജയം",
        FAILED: "പരാജയപ്പെട്ടു",
        DROPPED: "ഉപേക്ഷിച്ചു",
        DISPUTE: "വിവാദം",
        PENDING: "തീർച്ചപ്പെടുത്താത്ത",
        IMAGE_PENDING: "ഇമേജ് തീർച്ചപ്പെടുത്താത്ത",
        DUPLICATE: "ഡ്യൂപ്ലിക്കേറ്റ്",
        BANK_MISMATCH: "ബാങ്ക് പൊരുത്തക്കേട്",
        paymentUrlExpired: "പേയ്‌മെന്റ് URL കാലഹരണപ്പെട്ടു",
        EXPIRED: "കാലഹരണപ്പെട്ടു",
        paymentUrlExpiredTryAgain: "പേയ്‌മെന്റ് URL കാലഹരണപ്പെട്ടു. വീണ്ടും ശ്രമിക്കുക.",
        paymentSuccess: "പേയ്‌മെന്റ് വിജയകരമായി നടന്നു",
        pointsCreditedSoon: "നിന്റെ പോയിന്റുകൾ ഉടൻ നിന്റെ അക്കൗണ്ടിൽ ക്രെഡിറ്റ് ചെയ്യപ്പെടും"


    },
};